In [5]:
#source: https://data.statmt.org/news-commentary/v18.1/training/news-commentary-v18.de-en.tsv
import os
os.chdir("..")
# Path to the .bz2 file

In [6]:
os.getcwd()

'/Users/zp3077/Personal/Projects/translations_exploration'

In [7]:
import pandas as pd

file_path = 'data/news-commentary-v18.de-en.tsv'

In [9]:
df = pd.read_csv(file_path, sep='\t', header=None, on_bad_lines='skip')

In [10]:
df.columns = ['de', 'en']

In [11]:
df

,de,en
0,Steigt Gold auf 10.000 Dollar?,"$10,000 Gold?"
1,"SAN FRANCISCO – Es war noch nie leicht, ein ra...",SAN FRANCISCO – It has never been easy to have...
2,In letzter Zeit allerdings ist dies schwierige...,"Lately, with gold prices up more than 300% ove..."
3,Erst letzten Dezember verfassten meine Kollege...,"Just last December, fellow economists Martin F..."
4,"Und es kam, wie es kommen musste.",Wouldn’t you know it?
...,...,...
447989,Gleichzeitig scheint sich Zumas revolutionäre ...,"At the same time, Zuma’s revolutionary generat..."
447990,"In einer Region, wo die älteren Menschen sehr ...","In a region that reveres the elderly, Zuma’s a..."
447991,Drei von zehn Südafrikanern sind jünger als 15...,Three in ten South Africans are younger than 1...
447992,"Irgendwie muss Zuma einen Weg finden, einersei...",Somehow Zuma must find a way to honor his own ...
447993,NaN,NaN

In [12]:
df.isna().sum()

de    11452
en    11363
dtype: int64

In [13]:
df.dropna(inplace=True)

In [14]:
df.shape

(436208, 2)

In [15]:
sample_df = df.sample(50)

In [16]:
sample_df

,de,en
144986,Der Sieg Michail Saakaschwilis bei der Präside...,Mikhail Saakashvili's victory in Georgia's pre...
338605,In Brasilien wurde der seit 2003 amtierende Lu...,"In Brazil, Luis Inácio Lula da Silva, in power..."
415416,Aber dieser Ansatz hatte nur mäßigen Erfolg.,But this approach has had minimal impact.
225262,"Zwar stimmt es, dass Brasiliens Staatsverschul...","True, Brazil’s government debt is projected to..."
447425,Sie sind nahezu ausnahmslos Judenfeinde.,They were almost invariably anti-Semitic.
310744,Gerechtigkeit und Moral haben wenig damit zu tun.,Justice and morality have little to do with this.
282334,Dabei handelt es sich allesamt um produktive I...,"All of these are productive, but each has a di..."
379042,"Nun sieht es sicher so aus, als käme diese.",Now recession looks certain.
233781,Das US-Schatzamt unter Robert Rubin und Larry ...,The US Treasury under Robert Rubin and Larry S...
217007,Zwangsläufig weisen Fundamentalisten religiöse...,"Invariably, fundamentalists dismiss religious ..."
417000,"Heute besteht das große Problem darin, dass an...","Today, the big problem is that otherwise sensi..."
213508,Aufsichtsräte: Wie ein Käfer auf dem Rücken,Boards on Their Backs
162160,Eigentumsrechte gewerblicher Unternehmen am gr...,Proprietary rights for commercial firms over t...
272159,Die Menschen sind in gewisser Weise sozial hei...,"People are, in a sense, socially homeless."
402396,Trumps Geschenk an China,Trump’s Gift to China
132546,"Trump war unfähig, seine eigenen Worte umzuset...",Trump was incapable of following through on hi...
47709,Nach diesem Vorbild könnten die Entwicklungshi...,"Following this model, countries’ aid budgets c..."
418466,Wartet die Fed mit dieser Anhebung der Leitzin...,If the Fed does not postpone rate increases un...
390087,"In den USA, die weithin als „Land der unbegren...","In the US, widely called “the land of opportun..."
76640,Wohin Sie auch schauen (mit Ausnahme vielleich...,"Everywhere we look (except, perhaps, in New Gu..."
224821,Zu den wichtigsten natürlichen Klimalösungen g...,Among the most important natural climate solut...
278820,Und in einer letzten Monat veröffentlichten Um...,And a poll released last month by the Chicago ...
404069,Aber paradoxerweise scheinen Trumps Angriffe a...,"But, paradoxically, Trump’s attacks on America..."
33425,Ich besuchte Pakistan als Staatsgast.,I was in Pakistan as a state guest.
405611,In vielen transnationalen Fragen kann die Stär...,"On many transnational issues, empowering other..."
290591,Gaddafis Strategie verhinderte das Wachstum st...,Qaddafi’s strategy stunted the growth of state...
403247,Das US-Steuerrecht war bereits lange vor Trump...,The US tax code was already regressive long be...
44358,Neben dem menschlichen Leiden verursacht dies ...,"Beyond the human suffering, this imposes high ..."
52758,"Er erwartete, die Wahl zu gewinnen und Großbri...",He expected to win and keep Britain in the EU.
264247,Die Wirtschaftstheorie hat für die Politik kei...,Economic theory does not provide an unambiguou...
155783,"Dies deutet darauf hin, dass wir bereit sein s...",This indicates we should be willing to spend p...
119090,"Schließlich weiß Putin, dass die Sanktionen Ru...","After all, Putin knows that sanctions are deva..."
101016,China seinerseits sollte einseitigen Militärma...,"For its part, China should renounce unilateral..."
312519,In den letzten Jahrzehnten des 20. Jahrhundert...,"In the last decades of the twentieth century, ..."
166167,Aufgrund dieser Zugewinne stellt die AfD eine ...,"Owing to these gains, the AfD poses a grave th..."
115358,Eine grundlegende Steuerreform – etwa indem ma...,"While gains from fundamental tax reform – say,..."
187316,CAMBRIDGE – Die ständigen Verbesserungen bei f...,CAMBRIDGE – The steady stream of improvements ...
58412,Genauso waren formelle multilaterale Verträge ...,"By the same token, formal multilateral treatie..."
123266,"Wir sehen Russland dabei zu, wie es einen brut...",We are watching Russia wage a brutal war of ag...
416201,Dieser Deflationsdruck aus China ließ sich auf...,The disinflationary pressure from China result...
376512,Die Wiederkehr der Tuberkulose,The Return of Tuberculosis
230719,Nicht ohne Grund haben einige der größten euro...,There is a reason why many of the largest Euro...
59401,Für Italien mit seinem tief gespaltenen politi...,"For Italy, with its deeply divided political e..."
383130,"Doch reicht kühle Rationalität aus, um einen e...",But will cool rationality be enough to create ...
162155,Wir wissen dies aus Fällen wie dem von John Mo...,We know that from such cases as that of John M...
40736,Die Kosten von 6.000 Dollar für einen durchsch...,"At $6,000, the average cost of a hip replaceme..."
171799,Vor einem Jahr behaupteten die meisten Wirtsch...,"A year ago, most pundits argued that this was ..."
51046,"Gewinnt in einem Land, das so stabil und polit...",If Brexit wins in a country as stable and poli...
71924,In Wirklichkeit gibt es kaum einen Unterschied...,"In reality, little distinguishes the maritime ..."
92308,Länger anhaltende Rezessionen in Ländern niedr...,Prolonged recessions in lower-income countries...

In [17]:
sample_df.to_csv('data/new_sample.csv', index=False)