In [1]:
import pandas as pd

from eval.translation_metrics import calc_bleurt_score, calc_comet_score, calc_dbleu_score, calc_ter_score
import os
import torch
from llama_cpp import Llama

from dotenv import load_dotenv
os.chdir("..")

In [2]:


# Load environment variables
load_dotenv()

True

In [3]:

print(torch.backends.mps.is_available())  # Should be True

True

In [6]:

llm = Llama.from_pretrained(
    repo_id="bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
    filename="Meta-Llama-3.1-8B-Instruct-IQ2_M.gguf",
)

Meta-Llama-3.1-8B-Instruct-IQ2_M.gguf:   0%|          | 0.00/2.95G [00:00<?, ?B/s]

llama_model_load_from_file_impl: using device Metal (Apple M3 Pro) - 27647 MiB free
llama_model_loader: loaded meta data with 33 key-value pairs and 292 tensors from /Users/zp3077/.cache/huggingface/hub/models--bartowski--Meta-Llama-3.1-8B-Instruct-GGUF/snapshots/bf5b95e96dac0462e2a09145ec66cae9a3f12067/./Meta-Llama-3.1-8B-Instruct-IQ2_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = Meta Llama 3.1 8B Instruct
llama_model_loader: - kv   3:                           general.finetune str              = Instruct
llama_model_loader: - kv   4:                           general.basename str              = Meta-Llama-3.1
llama_model_loader: - kv   5:                         general.size_label str              = 8B
llama_model_loader: - kv   6:                            general.license str              = llama3.1
llama_model_loader: - kv   7:                               general.tags arr[str,6]       = ["facebook", "meta", "pytorch", "llam...
llama_model_loader: - kv   8:                          general.languages arr[str,8]       = ["en", "de", "fr", "it", "pt", "hi", ...
llama_model_loader: - kv   9:                          llama.block_count u32              = 32
llama_model_loader: - kv  10:                       llama.context_length u32              = 131072
llama_model_loader: - kv  11:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv  12:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv  13:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv  14:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv  15:                       llama.rope.freq_base f32              = 500000.000000
llama_model_loader: - kv  16:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  17:                          general.file_type u32              = 29
llama_model_loader: - kv  18:                           llama.vocab_size u32              = 128256
llama_model_loader: - kv  19:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv  20:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  21:                         tokenizer.ggml.pre str              = llama-bpe
llama_model_loader: - kv  22:                      tokenizer.ggml.tokens arr[str,128256]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  23:                  tokenizer.ggml.token_type arr[i32,128256]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  24:                      tokenizer.ggml.merges arr[str,280147]  = ["Ġ Ġ", "Ġ ĠĠĠ", "ĠĠ ĠĠ", "...
llama_model_loader: - kv  25:                tokenizer.ggml.bos_token_id u32              = 128000
llama_model_loader: - kv  26:                tokenizer.ggml.eos_token_id u32              = 128009
llama_model_loader: - kv  27:                    tokenizer.chat_template str              = {{- bos_token }}\n{%- if custom_tools ...
llama_model_loader: - kv  28:               general.quantization_version u32              = 2
llama_model_loader: - kv  29:                      quantize.imatrix.file str              = /models_out/Meta-Llama-3.1-8B-Instruc...
llama_model_loader: - kv  30:                   quantize.imatrix.dataset str              = /training_dir/calibration_datav3.txt
llama_model_loader: - kv  31:             quantize.imatrix.entries_count i32              = 224
llama_model_loader: - kv  32:              quantize.imatrix.chunks_count i32              = 125
llama_model_loader: - type  f32:   66 tensors
llama_model_loader: - type q4_K:   32 tensors
llama_model_loader: - type q5_K:    1 tensors
llama_model_loader: - type iq3_s:   37 tensors
llama_model_loader: - type iq2_s:  156 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = IQ2_M - 2.7 bpw
print_info: file size   = 2.74 GiB (2.93 BPW)
init_tokenizer: initializing tokenizer for type 2
load: control token: 128254 '<|reserved_special_token_246|>' is not marked as EOG
load: control token: 128252 '<|reserved_special_token_244|>' is not marked as EOG
load: control token: 128251 '<|reserved_special_token_243|>' is not marked as EOG
load: control token: 128250 '<|reserved_special_token_242|>' is not marked as EOG
load: control token: 128248 '<|reserved_special_token_240|>' is not marked as EOG
load: control token: 128247 '<|reserved_special_token_239|>' is not marked as EOG
load: control token: 128245 '<|reserved_special_token_237|>' is not marked as EOG
load: control token: 128244 '<|reserved_special_token_236|>' is not marked as EOG
load: control token: 128243 '<|reserved_special_token_235|>' is not marked as EOG
load: control token: 128240 '<|reserved_special_token_232|>' is not marked as EOG
load: control token: 128238 '<|reserved_special_token_230|>' is not marked as EOG
load: control token: 128235 '<|reserved_special_token_227|>' is not marked as EOG
load: control token: 128234 '<|reserved_special_token_226|>' is not marked as EOG
load: control token: 128229 '<|reserved_special_token_221|>' is not marked as EOG
load: control token: 128227 '<|reserved_special_token_219|>' is not marked as EOG
load: control token: 128226 '<|reserved_special_token_218|>' is not marked as EOG
load: control token: 128224 '<|reserved_special_token_216|>' is not marked as EOG
load: control token: 128223 '<|reserved_special_token_215|>' is not marked as EOG
load: control token: 128221 '<|reserved_special_token_213|>' is not marked as EOG
load: control token: 128219 '<|reserved_special_token_211|>' is not marked as EOG
load: control token: 128218 '<|reserved_special_token_210|>' is not marked as EOG
load: control token: 128217 '<|reserved_special_token_209|>' is not marked as EOG
load: control token: 128216 '<|reserved_special_token_208|>' is not marked as EOG
load: control token: 128215 '<|reserved_special_token_207|>' is not marked as EOG
load: control token: 128213 '<|reserved_special_token_205|>' is not marked as EOG
load: control token: 128211 '<|reserved_special_token_203|>' is not marked as EOG
load: control token: 128210 '<|reserved_special_token_202|>' is not marked as EOG
load: control token: 128209 '<|reserved_special_token_201|>' is not marked as EOG
load: control token: 128208 '<|reserved_special_token_200|>' is not marked as EOG
load: control token: 128207 '<|reserved_special_token_199|>' is not marked as EOG
load: control token: 128204 '<|reserved_special_token_196|>' is not marked as EOG
load: control token: 128202 '<|reserved_special_token_194|>' is not marked as EOG
load: control token: 128197 '<|reserved_special_token_189|>' is not marked as EOG
load: control token: 128195 '<|reserved_special_token_187|>' is not marked as EOG
load: control token: 128194 '<|reserved_special_token_186|>' is not marked as EOG
load: control token: 128191 '<|reserved_special_token_183|>' is not marked as EOG
load: control token: 128190 '<|reserved_special_token_182|>' is not marked as EOG
load: control token: 128188 '<|reserved_special_token_180|>' is not marked as EOG
load: control token: 128187 '<|reserved_special_token_179|>' is not marked as EOG
load: control token: 128185 '<|reserved_special_token_177|>' is not marked as EOG
load: control token: 128184 '<|reserved_special_token_176|>' is not marked as EOG
load: control token: 128183 '<|reserved_special_token_175|>' is not marked as EOG
load: control token: 128178 '<|reserved_special_token_170|>' is not marked as EOG
load: control token: 128177 '<|reserved_special_token_169|>' is not marked as EOG
load: control token: 128176 '<|reserved_special_token_168|>' is not marked as EOG
load: control token: 128175 '<|reserved_special_token_167|>' is not marked as EOG
load: control token: 128174 '<|reserved_special_token_166|>' is not marked as EOG
load: control token: 128173 '<|reserved_special_token_165|>' is not marked as EOG
load: control token: 128172 '<|reserved_special_token_164|>' is not marked as EOG
load: control token: 128169 '<|reserved_special_token_161|>' is not marked as EOG
load: control token: 128167 '<|reserved_special_token_159|>' is not marked as EOG
load: control token: 128166 '<|reserved_special_token_158|>' is not marked as EOG
load: control token: 128160 '<|reserved_special_token_152|>' is not marked as EOG
load: control token: 128159 '<|reserved_special_token_151|>' is not marked as EOG
load: control token: 128157 '<|reserved_special_token_149|>' is not marked as EOG
load: control token: 128156 '<|reserved_special_token_148|>' is not marked as EOG
load: control token: 128154 '<|reserved_special_token_146|>' is not marked as EOG
load: control token: 128152 '<|reserved_special_token_144|>' is not marked as EOG
load: control token: 128151 '<|reserved_special_token_143|>' is not marked as EOG
load: control token: 128150 '<|reserved_special_token_142|>' is not marked as EOG
load: control token: 128147 '<|reserved_special_token_139|>' is not marked as EOG
load: control token: 128144 '<|reserved_special_token_136|>' is not marked as EOG
load: control token: 128142 '<|reserved_special_token_134|>' is not marked as EOG
load: control token: 128141 '<|reserved_special_token_133|>' is not marked as EOG
load: control token: 128140 '<|reserved_special_token_132|>' is not marked as EOG
load: control token: 128133 '<|reserved_special_token_125|>' is not marked as EOG
load: control token: 128130 '<|reserved_special_token_122|>' is not marked as EOG
load: control token: 128128 '<|reserved_special_token_120|>' is not marked as EOG
load: control token: 128127 '<|reserved_special_token_119|>' is not marked as EOG
load: control token: 128126 '<|reserved_special_token_118|>' is not marked as EOG
load: control token: 128125 '<|reserved_special_token_117|>' is not marked as EOG
load: control token: 128124 '<|reserved_special_token_116|>' is not marked as EOG
load: control token: 128123 '<|reserved_special_token_115|>' is not marked as EOG
load: control token: 128122 '<|reserved_special_token_114|>' is not marked as EOG
load: control token: 128121 '<|reserved_special_token_113|>' is not marked as EOG
load: control token: 128120 '<|reserved_special_token_112|>' is not marked as EOG
load: control token: 128119 '<|reserved_special_token_111|>' is not marked as EOG
load: control token: 128116 '<|reserved_special_token_108|>' is not marked as EOG
load: control token: 128115 '<|reserved_special_token_107|>' is not marked as EOG
load: control token: 128114 '<|reserved_special_token_106|>' is not marked as EOG
load: control token: 128113 '<|reserved_special_token_105|>' is not marked as EOG
load: control token: 128111 '<|reserved_special_token_103|>' is not marked as EOG
load: control token: 128110 '<|reserved_special_token_102|>' is not marked as EOG
load: control token: 128107 '<|reserved_special_token_99|>' is not marked as EOG
load: control token: 128106 '<|reserved_special_token_98|>' is not marked as EOG
load: control token: 128105 '<|reserved_special_token_97|>' is not marked as EOG
load: control token: 128104 '<|reserved_special_token_96|>' is not marked as EOG
load: control token: 128103 '<|reserved_special_token_95|>' is not marked as EOG
load: control token: 128100 '<|reserved_special_token_92|>' is not marked as EOG
load: control token: 128097 '<|reserved_special_token_89|>' is not marked as EOG
load: control token: 128096 '<|reserved_special_token_88|>' is not marked as EOG
load: control token: 128094 '<|reserved_special_token_86|>' is not marked as EOG
load: control token: 128093 '<|reserved_special_token_85|>' is not marked as EOG
load: control token: 128090 '<|reserved_special_token_82|>' is not marked as EOG
load: control token: 128089 '<|reserved_special_token_81|>' is not marked as EOG
load: control token: 128087 '<|reserved_special_token_79|>' is not marked as EOG
load: control token: 128085 '<|reserved_special_token_77|>' is not marked as EOG
load: control token: 128080 '<|reserved_special_token_72|>' is not marked as EOG
load: control token: 128077 '<|reserved_special_token_69|>' is not marked as EOG
load: control token: 128076 '<|reserved_special_token_68|>' is not marked as EOG
load: control token: 128073 '<|reserved_special_token_65|>' is not marked as EOG
load: control token: 128070 '<|reserved_special_token_62|>' is not marked as EOG
load: control token: 128069 '<|reserved_special_token_61|>' is not marked as EOG
load: control token: 128067 '<|reserved_special_token_59|>' is not marked as EOG
load: control token: 128064 '<|reserved_special_token_56|>' is not marked as EOG
load: control token: 128062 '<|reserved_special_token_54|>' is not marked as EOG
load: control token: 128061 '<|reserved_special_token_53|>' is not marked as EOG
load: control token: 128060 '<|reserved_special_token_52|>' is not marked as EOG
load: control token: 128054 '<|reserved_special_token_46|>' is not marked as EOG
load: control token: 128045 '<|reserved_special_token_37|>' is not marked as EOG
load: control token: 128044 '<|reserved_special_token_36|>' is not marked as EOG
load: control token: 128043 '<|reserved_special_token_35|>' is not marked as EOG
load: control token: 128042 '<|reserved_special_token_34|>' is not marked as EOG
load: control token: 128038 '<|reserved_special_token_30|>' is not marked as EOG
load: control token: 128037 '<|reserved_special_token_29|>' is not marked as EOG
load: control token: 128035 '<|reserved_special_token_27|>' is not marked as EOG
load: control token: 128034 '<|reserved_special_token_26|>' is not marked as EOG
load: control token: 128033 '<|reserved_special_token_25|>' is not marked as EOG
load: control token: 128032 '<|reserved_special_token_24|>' is not marked as EOG
load: control token: 128030 '<|reserved_special_token_22|>' is not marked as EOG
load: control token: 128029 '<|reserved_special_token_21|>' is not marked as EOG
load: control token: 128028 '<|reserved_special_token_20|>' is not marked as EOG
load: control token: 128026 '<|reserved_special_token_18|>' is not marked as EOG
load: control token: 128025 '<|reserved_special_token_17|>' is not marked as EOG
load: control token: 128024 '<|reserved_special_token_16|>' is not marked as EOG
load: control token: 128022 '<|reserved_special_token_14|>' is not marked as EOG
load: control token: 128020 '<|reserved_special_token_12|>' is not marked as EOG
load: control token: 128017 '<|reserved_special_token_9|>' is not marked as EOG
load: control token: 128016 '<|reserved_special_token_8|>' is not marked as EOG
load: control token: 128015 '<|reserved_special_token_7|>' is not marked as EOG
load: control token: 128014 '<|reserved_special_token_6|>' is not marked as EOG
load: control token: 128013 '<|reserved_special_token_5|>' is not marked as EOG
load: control token: 128011 '<|reserved_special_token_3|>' is not marked as EOG
load: control token: 128010 '<|python_tag|>' is not marked as EOG
load: control token: 128006 '<|start_header_id|>' is not marked as EOG
load: control token: 128003 '<|reserved_special_token_1|>' is not marked as EOG
load: control token: 128002 '<|reserved_special_token_0|>' is not marked as EOG
load: control token: 128000 '<|begin_of_text|>' is not marked as EOG
load: control token: 128041 '<|reserved_special_token_33|>' is not marked as EOG
load: control token: 128063 '<|reserved_special_token_55|>' is not marked as EOG
load: control token: 128046 '<|reserved_special_token_38|>' is not marked as EOG
load: control token: 128007 '<|end_header_id|>' is not marked as EOG
load: control token: 128065 '<|reserved_special_token_57|>' is not marked as EOG
load: control token: 128171 '<|reserved_special_token_163|>' is not marked as EOG
load: control token: 128162 '<|reserved_special_token_154|>' is not marked as EOG
load: control token: 128165 '<|reserved_special_token_157|>' is not marked as EOG
load: control token: 128057 '<|reserved_special_token_49|>' is not marked as EOG
load: control token: 128050 '<|reserved_special_token_42|>' is not marked as EOG
load: control token: 128056 '<|reserved_special_token_48|>' is not marked as EOG
load: control token: 128230 '<|reserved_special_token_222|>' is not marked as EOG
load: control token: 128098 '<|reserved_special_token_90|>' is not marked as EOG
load: control token: 128153 '<|reserved_special_token_145|>' is not marked as EOG
load: control token: 128084 '<|reserved_special_token_76|>' is not marked as EOG
load: control token: 128082 '<|reserved_special_token_74|>' is not marked as EOG
load: control token: 128102 '<|reserved_special_token_94|>' is not marked as EOG
load: control token: 128253 '<|reserved_special_token_245|>' is not marked as EOG
load: control token: 128179 '<|reserved_special_token_171|>' is not marked as EOG
load: control token: 128071 '<|reserved_special_token_63|>' is not marked as EOG
load: control token: 128135 '<|reserved_special_token_127|>' is not marked as EOG
load: control token: 128161 '<|reserved_special_token_153|>' is not marked as EOG
load: control token: 128164 '<|reserved_special_token_156|>' is not marked as EOG
load: control token: 128134 '<|reserved_special_token_126|>' is not marked as EOG
load: control token: 128249 '<|reserved_special_token_241|>' is not marked as EOG
load: control token: 128004 '<|finetune_right_pad_id|>' is not marked as EOG
load: control token: 128036 '<|reserved_special_token_28|>' is not marked as EOG
load: control token: 128148 '<|reserved_special_token_140|>' is not marked as EOG
load: control token: 128181 '<|reserved_special_token_173|>' is not marked as EOG
load: control token: 128222 '<|reserved_special_token_214|>' is not marked as EOG
load: control token: 128075 '<|reserved_special_token_67|>' is not marked as EOG
load: control token: 128241 '<|reserved_special_token_233|>' is not marked as EOG
load: control token: 128051 '<|reserved_special_token_43|>' is not marked as EOG
load: control token: 128068 '<|reserved_special_token_60|>' is not marked as EOG
load: control token: 128149 '<|reserved_special_token_141|>' is not marked as EOG
load: control token: 128201 '<|reserved_special_token_193|>' is not marked as EOG
load: control token: 128058 '<|reserved_special_token_50|>' is not marked as EOG
load: control token: 128146 '<|reserved_special_token_138|>' is not marked as EOG
load: control token: 128143 '<|reserved_special_token_135|>' is not marked as EOG
load: control token: 128023 '<|reserved_special_token_15|>' is not marked as EOG
load: control token: 128039 '<|reserved_special_token_31|>' is not marked as EOG
load: control token: 128132 '<|reserved_special_token_124|>' is not marked as EOG
load: control token: 128101 '<|reserved_special_token_93|>' is not marked as EOG
load: control token: 128212 '<|reserved_special_token_204|>' is not marked as EOG
load: control token: 128189 '<|reserved_special_token_181|>' is not marked as EOG
load: control token: 128225 '<|reserved_special_token_217|>' is not marked as EOG
load: control token: 128129 '<|reserved_special_token_121|>' is not marked as EOG
load: control token: 128005 '<|reserved_special_token_2|>' is not marked as EOG
load: control token: 128078 '<|reserved_special_token_70|>' is not marked as EOG
load: control token: 128163 '<|reserved_special_token_155|>' is not marked as EOG
load: control token: 128072 '<|reserved_special_token_64|>' is not marked as EOG
load: control token: 128112 '<|reserved_special_token_104|>' is not marked as EOG
load: control token: 128186 '<|reserved_special_token_178|>' is not marked as EOG

In [8]:
def translate(input_text):
    output = llm(
        f"""Translate the following German text to English. Only return the translated text, nothing else.\n"
        "German: {input_text}r\n"
        "English:""",
        max_tokens=50,  # Limit the response length
        stop=["\n"],  # Stops generation at the first newline to avoid extra text
        temperature=0  # Makes the output deterministic
    )
    return output['choices'][0]['text']

In [10]:
translate("Ich hate gern pizza")

Llama.generate: 23 prefix-match hit, remaining 13 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    3234.76 ms /    13 tokens (  248.83 ms per token,     4.02 tokens per second)
llama_perf_context_print:        eval time =     321.94 ms /     3 runs   (  107.31 ms per token,     9.32 tokens per second)
llama_perf_context_print:       total time =    3557.91 ms /    16 tokens

' I love pizza"'

In [11]:


df = pd.read_csv('data/new_sample.csv')

In [12]:
df['en_transalted'] = df['de'].apply(translate)

Llama.generate: 23 prefix-match hit, remaining 70 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2629.27 ms /    70 tokens (   37.56 ms per token,    26.62 tokens per second)
llama_perf_context_print:        eval time =    4754.65 ms /    44 runs   (  108.06 ms per token,     9.25 tokens per second)
llama_perf_context_print:       total time =    7392.37 ms /   114 tokens
Llama.generate: 23 prefix-match hit, remaining 73 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2527.40 ms /    73 tokens (   34.62 ms per token,    28.88 tokens per second)
llama_perf_context_print:        eval time =    3806.84 ms /    38 runs   (  100.18 ms per token,     9.98 tokens per second)
llama_perf_context_print:       total time =    6341.16 ms /   111 tokens
Llama.generate: 23 prefix-match hit, remaining 18 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2817.06 ms /    18 tokens (  156.50 ms per token,     6.39 tokens per second)
llama_perf_context_print:        eval time =     907.69 ms /     9 runs   (  100.85 ms per token,     9.92 tokens per second)
llama_perf_context_print:       total time =    3726.38 ms /    27 tokens
Llama.generate: 23 prefix-match hit, remaining 41 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2060.54 ms /    41 tokens (   50.26 ms per token,    19.90 tokens per second)
llama_perf_context_print:        eval time =    2918.30 ms /    29 runs   (  100.63 ms per token,     9.94 tokens per second)
llama_perf_context_print:       total time =    4983.88 ms /    70 tokens
Llama.generate: 23 prefix-match hit, remaining 20 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2161.98 ms /    20 tokens (  108.10 ms per token,     9.25 tokens per second)
llama_perf_context_print:        eval time =     604.55 ms /     6 runs   (  100.76 ms per token,     9.92 tokens per second)
llama_perf_context_print:       total time =    2767.96 ms /    26 tokens
Llama.generate: 23 prefix-match hit, remaining 18 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    1336.58 ms /    18 tokens (   74.25 ms per token,    13.47 tokens per second)
llama_perf_context_print:        eval time =     902.96 ms /     9 runs   (  100.33 ms per token,     9.97 tokens per second)
llama_perf_context_print:       total time =    2241.14 ms /    27 tokens
Llama.generate: 23 prefix-match hit, remaining 42 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2784.71 ms /    42 tokens (   66.30 ms per token,    15.08 tokens per second)
llama_perf_context_print:        eval time =       0.00 ms /     1 runs   (    0.00 ms per token,      inf tokens per second)
llama_perf_context_print:       total time =    2784.96 ms /    43 tokens
Llama.generate: 23 prefix-match hit, remaining 18 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    1736.16 ms /    18 tokens (   96.45 ms per token,    10.37 tokens per second)
llama_perf_context_print:        eval time =    1397.39 ms /    13 runs   (  107.49 ms per token,     9.30 tokens per second)
llama_perf_context_print:       total time =    3136.36 ms /    31 tokens
Llama.generate: 23 prefix-match hit, remaining 61 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2320.37 ms /    61 tokens (   38.04 ms per token,    26.29 tokens per second)
llama_perf_context_print:        eval time =    3979.78 ms /    38 runs   (  104.73 ms per token,     9.55 tokens per second)
llama_perf_context_print:       total time =    6306.83 ms /    99 tokens
Llama.generate: 23 prefix-match hit, remaining 55 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2075.28 ms /    55 tokens (   37.73 ms per token,    26.50 tokens per second)
llama_perf_context_print:        eval time =    1922.42 ms /    19 runs   (  101.18 ms per token,     9.88 tokens per second)
llama_perf_context_print:       total time =    4001.11 ms /    74 tokens
Llama.generate: 23 prefix-match hit, remaining 81 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2568.25 ms /    81 tokens (   31.71 ms per token,    31.54 tokens per second)
llama_perf_context_print:        eval time =    4949.81 ms /    48 runs   (  103.12 ms per token,     9.70 tokens per second)
llama_perf_context_print:       total time =    7526.64 ms /   129 tokens
Llama.generate: 23 prefix-match hit, remaining 23 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    1800.68 ms /    23 tokens (   78.29 ms per token,    12.77 tokens per second)
llama_perf_context_print:        eval time =    1332.30 ms /    13 runs   (  102.48 ms per token,     9.76 tokens per second)
llama_perf_context_print:       total time =    3135.32 ms /    36 tokens
Llama.generate: 23 prefix-match hit, remaining 36 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    1978.26 ms /    36 tokens (   54.95 ms per token,    18.20 tokens per second)
llama_perf_context_print:        eval time =    2204.11 ms /    22 runs   (  100.19 ms per token,     9.98 tokens per second)
llama_perf_context_print:       total time =    4186.60 ms /    58 tokens
Llama.generate: 23 prefix-match hit, remaining 20 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    1647.46 ms /    20 tokens (   82.37 ms per token,    12.14 tokens per second)
llama_perf_context_print:        eval time =     892.03 ms /     9 runs   (   99.11 ms per token,    10.09 tokens per second)
llama_perf_context_print:       total time =    2541.22 ms /    29 tokens
Llama.generate: 23 prefix-match hit, remaining 14 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    1978.98 ms /    14 tokens (  141.36 ms per token,     7.07 tokens per second)
llama_perf_context_print:        eval time =     500.27 ms /     5 runs   (  100.05 ms per token,     9.99 tokens per second)
llama_perf_context_print:       total time =    2480.36 ms /    19 tokens
Llama.generate: 24 prefix-match hit, remaining 32 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    1786.28 ms /    32 tokens (   55.82 ms per token,    17.91 tokens per second)
llama_perf_context_print:        eval time =    2129.66 ms /    21 runs   (  101.41 ms per token,     9.86 tokens per second)
llama_perf_context_print:       total time =    3919.92 ms /    53 tokens
Llama.generate: 23 prefix-match hit, remaining 106 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2689.25 ms /   106 tokens (   25.37 ms per token,    39.42 tokens per second)
llama_perf_context_print:        eval time =    5074.21 ms /    49 runs   (  103.56 ms per token,     9.66 tokens per second)
llama_perf_context_print:       total time =    7772.71 ms /   155 tokens
Llama.generate: 23 prefix-match hit, remaining 62 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2116.43 ms /    62 tokens (   34.14 ms per token,    29.29 tokens per second)
llama_perf_context_print:        eval time =    3477.53 ms /    35 runs   (   99.36 ms per token,    10.06 tokens per second)
llama_perf_context_print:       total time =    5599.96 ms /    97 tokens
Llama.generate: 23 prefix-match hit, remaining 87 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2381.08 ms /    87 tokens (   27.37 ms per token,    36.54 tokens per second)
llama_perf_context_print:        eval time =    5999.59 ms /    49 runs   (  122.44 ms per token,     8.17 tokens per second)
llama_perf_context_print:       total time =    8391.54 ms /   136 tokens
Llama.generate: 23 prefix-match hit, remaining 68 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2489.09 ms /    68 tokens (   36.60 ms per token,    27.32 tokens per second)
llama_perf_context_print:        eval time =    3263.01 ms /    33 runs   (   98.88 ms per token,    10.11 tokens per second)
llama_perf_context_print:       total time =    5757.56 ms /   101 tokens
Llama.generate: 23 prefix-match hit, remaining 60 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2059.54 ms /    60 tokens (   34.33 ms per token,    29.13 tokens per second)
llama_perf_context_print:        eval time =    3858.85 ms /    37 runs   (  104.29 ms per token,     9.59 tokens per second)
llama_perf_context_print:       total time =    5925.11 ms /    97 tokens
Llama.generate: 23 prefix-match hit, remaining 99 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2712.77 ms /    99 tokens (   27.40 ms per token,    36.49 tokens per second)
llama_perf_context_print:        eval time =    5973.07 ms /    49 runs   (  121.90 ms per token,     8.20 tokens per second)
llama_perf_context_print:       total time =    8696.23 ms /   148 tokens
Llama.generate: 23 prefix-match hit, remaining 38 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2323.52 ms /    38 tokens (   61.15 ms per token,    16.35 tokens per second)
llama_perf_context_print:        eval time =    2183.03 ms /    21 runs   (  103.95 ms per token,     9.62 tokens per second)
llama_perf_context_print:       total time =    4510.59 ms /    59 tokens
Llama.generate: 23 prefix-match hit, remaining 17 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    1433.78 ms /    17 tokens (   84.34 ms per token,    11.86 tokens per second)
llama_perf_context_print:        eval time =     888.44 ms /     9 runs   (   98.72 ms per token,    10.13 tokens per second)
llama_perf_context_print:       total time =    2323.79 ms /    26 tokens
Llama.generate: 23 prefix-match hit, remaining 35 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2344.35 ms /    35 tokens (   66.98 ms per token,    14.93 tokens per second)
llama_perf_context_print:        eval time =    2146.15 ms /    20 runs   (  107.31 ms per token,     9.32 tokens per second)
llama_perf_context_print:       total time =    4494.31 ms /    55 tokens
Llama.generate: 23 prefix-match hit, remaining 65 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2559.52 ms /    65 tokens (   39.38 ms per token,    25.40 tokens per second)
llama_perf_context_print:        eval time =    3989.51 ms /    39 runs   (  102.30 ms per token,     9.78 tokens per second)
llama_perf_context_print:       total time =    6555.98 ms /   104 tokens
Llama.generate: 23 prefix-match hit, remaining 73 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2601.63 ms /    73 tokens (   35.64 ms per token,    28.06 tokens per second)
llama_perf_context_print:        eval time =    4444.90 ms /    45 runs   (   98.78 ms per token,    10.12 tokens per second)
llama_perf_context_print:       total time =    7054.44 ms /   118 tokens
Llama.generate: 23 prefix-match hit, remaining 26 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2161.59 ms /    26 tokens (   83.14 ms per token,    12.03 tokens per second)
llama_perf_context_print:        eval time =    1388.08 ms /    14 runs   (   99.15 ms per token,    10.09 tokens per second)
llama_perf_context_print:       total time =    3552.02 ms /    40 tokens
Llama.generate: 23 prefix-match hit, remaining 28 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2050.58 ms /    28 tokens (   73.23 ms per token,    13.65 tokens per second)
llama_perf_context_print:        eval time =    1289.23 ms /    13 runs   (   99.17 ms per token,    10.08 tokens per second)
llama_perf_context_print:       total time =    3342.08 ms /    41 tokens
Llama.generate: 23 prefix-match hit, remaining 25 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    1813.57 ms /    25 tokens (   72.54 ms per token,    13.78 tokens per second)
llama_perf_context_print:        eval time =     989.08 ms /    10 runs   (   98.91 ms per token,    10.11 tokens per second)
llama_perf_context_print:       total time =    2804.55 ms /    35 tokens
Llama.generate: 23 prefix-match hit, remaining 79 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2391.88 ms /    79 tokens (   30.28 ms per token,    33.03 tokens per second)
llama_perf_context_print:        eval time =    4544.17 ms /    40 runs   (  113.60 ms per token,     8.80 tokens per second)
llama_perf_context_print:       total time =    6943.79 ms /   119 tokens
Llama.generate: 23 prefix-match hit, remaining 58 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2333.89 ms /    58 tokens (   40.24 ms per token,    24.85 tokens per second)
llama_perf_context_print:        eval time =    4104.93 ms /    38 runs   (  108.02 ms per token,     9.26 tokens per second)
llama_perf_context_print:       total time =    6445.87 ms /    96 tokens
Llama.generate: 23 prefix-match hit, remaining 72 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2744.79 ms /    72 tokens (   38.12 ms per token,    26.23 tokens per second)
llama_perf_context_print:        eval time =    3862.57 ms /    38 runs   (  101.65 ms per token,     9.84 tokens per second)
llama_perf_context_print:       total time =    6613.98 ms /   110 tokens
Llama.generate: 23 prefix-match hit, remaining 36 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2082.47 ms /    36 tokens (   57.85 ms per token,    17.29 tokens per second)
llama_perf_context_print:        eval time =    1978.93 ms /    20 runs   (   98.95 ms per token,    10.11 tokens per second)
llama_perf_context_print:       total time =    4064.89 ms /    56 tokens
Llama.generate: 23 prefix-match hit, remaining 44 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2024.69 ms /    44 tokens (   46.02 ms per token,    21.73 tokens per second)
llama_perf_context_print:        eval time =    2660.62 ms /    27 runs   (   98.54 ms per token,    10.15 tokens per second)
llama_perf_context_print:       total time =    4690.07 ms /    71 tokens
Llama.generate: 23 prefix-match hit, remaining 112 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2660.81 ms /   112 tokens (   23.76 ms per token,    42.09 tokens per second)
llama_perf_context_print:        eval time =    4998.22 ms /    49 runs   (  102.00 ms per token,     9.80 tokens per second)
llama_perf_context_print:       total time =    7667.59 ms /   161 tokens
Llama.generate: 23 prefix-match hit, remaining 65 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2291.24 ms /    65 tokens (   35.25 ms per token,    28.37 tokens per second)
llama_perf_context_print:        eval time =    3746.34 ms /    38 runs   (   98.59 ms per token,    10.14 tokens per second)
llama_perf_context_print:       total time =    6044.12 ms /   103 tokens
Llama.generate: 23 prefix-match hit, remaining 105 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2672.38 ms /   105 tokens (   25.45 ms per token,    39.29 tokens per second)
llama_perf_context_print:        eval time =    4864.89 ms /    49 runs   (   99.28 ms per token,    10.07 tokens per second)
llama_perf_context_print:       total time =    7545.48 ms /   154 tokens
Llama.generate: 23 prefix-match hit, remaining 85 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2439.06 ms /    85 tokens (   28.69 ms per token,    34.85 tokens per second)
llama_perf_context_print:        eval time =    3880.28 ms /    39 runs   (   99.49 ms per token,    10.05 tokens per second)
llama_perf_context_print:       total time =    6326.22 ms /   124 tokens
Llama.generate: 23 prefix-match hit, remaining 42 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2210.52 ms /    42 tokens (   52.63 ms per token,    19.00 tokens per second)
llama_perf_context_print:        eval time =    2200.04 ms /    22 runs   (  100.00 ms per token,    10.00 tokens per second)
llama_perf_context_print:       total time =    4414.48 ms /    64 tokens
Llama.generate: 23 prefix-match hit, remaining 15 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    1494.06 ms /    15 tokens (   99.60 ms per token,    10.04 tokens per second)
llama_perf_context_print:        eval time =     593.18 ms /     6 runs   (   98.86 ms per token,    10.11 tokens per second)
llama_perf_context_print:       total time =    2088.41 ms /    21 tokens
Llama.generate: 23 prefix-match hit, remaining 49 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2028.68 ms /    49 tokens (   41.40 ms per token,    24.15 tokens per second)
llama_perf_context_print:        eval time =    3260.04 ms /    33 runs   (   98.79 ms per token,    10.12 tokens per second)
llama_perf_context_print:       total time =    5294.44 ms /    82 tokens
Llama.generate: 23 prefix-match hit, remaining 50 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2048.98 ms /    50 tokens (   40.98 ms per token,    24.40 tokens per second)
llama_perf_context_print:        eval time =    2567.97 ms /    26 runs   (   98.77 ms per token,    10.12 tokens per second)
llama_perf_context_print:       total time =    4621.54 ms /    76 tokens
Llama.generate: 23 prefix-match hit, remaining 39 prompt tokens to eval
llama_perf_context_print:        load time =    3350.87 ms
llama_perf_context_print: prompt eval time =    2009.72 ms /    39 tokens (   51.53 ms per token,    19.41 tokens per second)

## Apply all the transaltion metrics.

In [13]:
from eval.translation_metrics import calc_bleurt_score, calc_comet_score, calc_dbleu_score, calc_ter_score

Using default BLEURT-Base checkpoint for sequence maximum length 128. You can use a bigger model for better results with e.g.: evaluate.load('bleurt', 'bleurt-large-512').

INFO:tensorflow:Reading checkpoint /Users/zp3077/.cache/huggingface/metrics/bleurt/default/downloads/extracted/d8b1bce334445f0def1d1a1c4851abc76d19672f541e0dcc15bf5eb22cfed174/bleurt-base-128.

Reading checkpoint /Users/zp3077/.cache/huggingface/metrics/bleurt/default/downloads/extracted/d8b1bce334445f0def1d1a1c4851abc76d19672f541e0dcc15bf5eb22cfed174/bleurt-base-128.

INFO:tensorflow:Config file found, reading.

Config file found, reading.

INFO:tensorflow:Will load checkpoint bert_custom

Will load checkpoint bert_custom

INFO:tensorflow:Loads full paths and checks that files exists.

Loads full paths and checks that files exists.

INFO:tensorflow:... name:bert_custom

... name:bert_custom

INFO:tensorflow:... vocab_file:vocab.txt

... vocab_file:vocab.txt

INFO:tensorflow:... bert_config_file:bert_config.json

... bert_config_file:bert_config.json

INFO:tensorflow:... do_lower_case:True

... do_lower_case:True

INFO:tensorflow:... max_seq_length:128

... max_seq_length:128

INFO:tensorflow:Creating BLEURT scorer.

Creating BLEURT scorer.

INFO:tensorflow:Creating WordPiece tokenizer.

Creating WordPiece tokenizer.

INFO:tensorflow:WordPiece tokenizer instantiated.

WordPiece tokenizer instantiated.

INFO:tensorflow:Creating Eager Mode predictor.

Creating Eager Mode predictor.

INFO:tensorflow:Loading model.

Loading model.
Fingerprint not found. Saved model loading will continue.
path_and_singleprint metric could not be logged. Saved model loading will continue.

INFO:tensorflow:BLEURT initialized.

BLEURT initialized.

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

Lightning automatically upgraded your loaded checkpoint from v1.8.3.post1 to v2.5.0.post0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../../.cache/huggingface/hub/models--Unbabel--wmt22-comet-da/snapshots/2760a223ac957f30acfb18c8aa649b01cf1d75f2/checkpoints/model.ckpt`
Encoder model frozen.
/Users/zp3077/Personal/Projects/translations_exploration/.venv/lib/python3.10/site-packages/pytorch_lightning/core/saving.py:195: Found keys that are not in the model state dict but in the checkpoint: ['encoder.model.embeddings.position_ids']

In [14]:
def calc_metrics(org_col: str , machine_translated_col: str, gd_translated_col: str, df: pd.DataFrame):
    '''
    This function will calculate the metrics for the given columns
    :param org_col: the column the text in original language
    :param machine_translated_col: the column with the machine translated text
    :param gd_translated_col: the column with the human translated text
    :param df: the dataframe with the data.
    :return:
    '''
    df['dbleu'] = df.apply(lambda x: calc_dbleu_score(x[gd_translated_col].lower(), x[machine_translated_col].lower()), axis=1)
    df['bleurt'] = df.apply(lambda x: calc_bleurt_score(x[gd_translated_col].lower(), x[machine_translated_col].lower()), axis=1)
    df['comet'] = df.apply(lambda x: calc_comet_score(x[org_col].lower(), x[gd_translated_col].lower(), x[machine_translated_col].lower()), axis=1)

    df[['ter_num_edits','ter_score']]  = df.apply(lambda x: pd.Series(calc_ter_score(x[gd_translated_col].lower(), x[machine_translated_col].lower())), axis=1)
    df['dbleu'] = df['dbleu'].astype(float)
    return df

In [15]:
df = calc_metrics('de', 'en_transalted', 'en', df)

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting: 0it [00:00, ?it/s]huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  2.69it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  3.88it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  3.84it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  3.88it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  7.47it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 14.32it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  3.83it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  7.37it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  5.63it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  3.68it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  3.78it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  7.95it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  5.58it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  5.57it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  7.43it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  7.87it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  6.13it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  4.06it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  5.13it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 12.16it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  4.54it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  4.13it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  8.20it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  6.95it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  6.33it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  7.03it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 10.40it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  6.26it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  6.15it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  6.81it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 12.39it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  3.94it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 11.60it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  6.91it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  4.29it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  5.33it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 12.23it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  4.78it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 11.68it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 11.23it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  6.62it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  6.59it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 10.22it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 11.18it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  6.71it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  6.04it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  6.37it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 10.91it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 10.24it/s]
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 10.70it/s]

In [16]:
df.head()

,de,en,en_transalted,dbleu,bleurt,comet,ter_num_edits,ter_score
0,Der Sieg Michail Saakaschwilis bei der Präside...,Mikhail Saakashvili's victory in Georgia's pre...,Mikhail Saakashvili's victory in the presiden...,33.981696,0.399565,0.847955,13.0,5.990783
1,In Brasilien wurde der seit 2003 amtierende Lu...,"In Brazil, Luis Inácio Lula da Silva, in power...","In Brazil, Lula da Silva was re-elected in 20...",44.237680,0.231080,0.884883,17.0,9.826590
2,Aber dieser Ansatz hatte nur mäßigen Erfolg.,But this approach has had minimal impact.,"But this approach had only moderate success.""r",18.190371,0.363515,0.852425,4.0,8.510638
3,"Zwar stimmt es, dass Brasiliens Staatsverschul...","True, Brazil’s government debt is projected to...","""Indeed, it is true that Brazil's public debt...",10.064971,0.373230,0.852465,14.0,10.852713
4,Sie sind nahezu ausnahmslos Judenfeinde.,They were almost invariably anti-Semitic.,"They are almost exclusively anti-Semitic.""",16.341219,0.712026,0.921928,3.0,6.976744

In [17]:
df[[ 'dbleu', 'comet', 'bleurt', 'ter_num_edits']].describe()

           dbleu      comet     bleurt  ter_num_edits
count  50.000000  50.000000  50.000000      50.000000
mean   30.387090   0.809796   0.128422      13.140000
std    18.758343   0.124227   0.505271       8.141629
min     0.000000   0.341300  -1.448337       1.000000
25%    14.460761   0.799906   0.116669       6.250000
50%    31.406301   0.838532   0.231229      12.000000
75%    43.314725   0.870108   0.378280      19.750000
max    70.807355   0.948245   0.840242      35.000000

In [18]:
def summarize_df(df):

    output = llm(
        f"""You are an AI assistant. Your task is to summarize the given pandas DataFrame into the main points. Please provide a concise summary for this dataframe :{df}""",
        max_tokens=512,  # Limit the response length
        stop=["\n"],  # Stops generation at the first newline to avoid extra text
        temperature=0  # Makes the output deterministic
    )
    return output['choices'][0]['text']

In [19]:
df[[ 'dbleu', 'comet', 'bleurt', 'ter_num_edits']].describe()

           dbleu      comet     bleurt  ter_num_edits
count  50.000000  50.000000  50.000000      50.000000
mean   30.387090   0.809796   0.128422      13.140000
std    18.758343   0.124227   0.505271       8.141629
min     0.000000   0.341300  -1.448337       1.000000
25%    14.460761   0.799906   0.116669       6.250000
50%    31.406301   0.838532   0.231229      12.000000
75%    43.314725   0.870108   0.378280      19.750000
max    70.807355   0.948245   0.840242      35.000000

## Llama 3.1 proved to be better model than the Eurollm

In [ ]:
summarize_df(df[[ 'dbleu', 'comet', 'bleurt', 'ter_num_edits']].describe())